import { Inter } from 'next/font/google'
import './globals.css'

import Navbar from '../client/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div
          id='content'
          className='p-2 w-full lg:container mx-auto gap-2 overflow-hidden h-screen'
        >
          <header className='[grid-area:nav]'>
            <Navbar />
          </header>

          <main className='[grid-area:main] grid gap-2'>{children}</main>
        </div>
      </body>
    </html>
  )
}
